export type StaticArticle = {
  slug: string;
  title: string;
  description: string;
  category: string;
  publishedAt: string;
  updatedAt: string;
  published: boolean;
};

export const staticArticles: Record<string, StaticArticle> = {
  'salaryman-setsuzei-14sen': {
    slug: 'salaryman-setsuzei-14sen',
    title: 'サラリーマンの節税対策14選｜会社員が今すぐ使える控除を完全解説【2026年版】',
    description: '年収500〜1,000万の会社員が今すぐ使える節税対策14選を徹底解説。医療費控除・ふるさと納税・iDeCoの節税シミュレーション付き。年末調整だけでは取りこぼす控除を発見して手取りを最大化しましょう。',
    category: 'サラリーマン節税',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'zeikin-haraisugichi-check': {
    slug: 'zeikin-haraisugichi-check',
    title: '税金払いすぎていませんか？5分でできる控除漏れセルフチェック法',
    description: '年末調整だけでは取りこぼす控除7選と、5分でできる控除漏れセルフチェック法を解説。過去5年分の還付申告で取り戻す方法も。',
    category: 'サラリーマン節税',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'tomobataraki-setsuzei-guide': {
    slug: 'tomobataraki-setsuzei-guide',
    title: '共働き夫婦の節税最適化ガイド',
    description: '共働き夫婦が陥りがちな節税ミス3選と、扶養控除・医療費控除・住宅ローン控除の最適な配分で世帯手取りを最大化する方法を解説。',
    category: '共働き節税',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'fukugyou-kakutei-shinkoku-guide': {
    slug: 'fukugyou-kakutei-shinkoku-guide',
    title: '副業の確定申告完全ガイド',
    description: '副業所得20万円ルールの正しい解釈・経費の判断基準・住民税の普通徴収で副業が会社にバレないための手続きを完全解説。',
    category: '副業・確定申告',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'kanpu-shinkoku-kako-5nen': {
    slug: 'kanpu-shinkoku-kako-5nen',
    title: '過去5年分の還付金を取り戻す方法',
    description: '控除漏れに気づいたら今からでも間に合う。還付申告の対象期間・必要書類・e-Taxでの申請手順を徹底解説。',
    category: '還付申告',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'nenshu-800man-setsuzei-8sen': {
    slug: 'nenshu-800man-setsuzei-8sen',
    title: '年収800万円の節税対策8選',
    description: '年収800万円の会社員が使える節税対策8選を年収別シミュレーション付きで解説。iDeCo・ふるさと納税・住宅ローン控除の最適な組み合わせ方。',
    category: '年収別節税',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'shotoku-kojo-16shurui-ichiran': {
    slug: 'shotoku-kojo-16shurui-ichiran',
    title: '所得控除16種類を一覧表で解説【2026年版】',
    description: '所得税・住民税を減らすための所得控除16種類を一覧表で完全網羅。使える条件・控除額・申請方法を2026年最新情報でまとめました。',
    category: 'サラリーマン節税',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'freelance-setsuzei-guide': {
    slug: 'freelance-setsuzei-guide',
    title: 'フリーランスの節税完全ガイド',
    description: 'フリーランス・個人事業主が使える節税手段を完全解説。青色申告・小規模企業共済・iDeCo・経費の扱いまでを網羅。',
    category: 'フリーランス節税',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  '50dai-taishoku-setsuzei-checklist': {
    slug: '50dai-taishoku-setsuzei-checklist',
    title: '50代の退職準備チェックリスト｜退職金・iDeCo・健康保険の節税ポイント',
    description: '50代で退職を考えている方向け。退職金・iDeCo・年金の受取順序・健康保険の切り替えなど、退職前にやるべき節税準備を完全チェックリスト化。',
    category: '退職・年金',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'nenmatsu-chosei-sonhinai-7kojo': {
    slug: 'nenmatsu-chosei-sonhinai-7kojo',
    title: '年末調整で損しない7つの控除',
    description: '年末調整で意外と申告漏れが多い7つの控除を解説。生命保険料・地震保険料・扶養控除・配偶者控除の記入ミスをゼロにする方法。',
    category: '年末調整',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'iryohi-kojo-urawaza-7sen': {
    slug: 'iryohi-kojo-urawaza-7sen',
    title: '医療費控除の裏技7選',
    description: '意外と知らない医療費控除の裏技7選。交通費・市販薬・出産費用・介護費用まで。家族合算で節税効果を最大化する方法を解説。',
    category: '医療費控除',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'iryohi-kojo-ikura-modoru': {
    slug: 'iryohi-kojo-ikura-modoru',
    title: '医療費控除でいくら戻る？年収別シミュレーション',
    description: '医療費控除で実際にいくら還付されるか年収別に計算。年収400万・600万・800万のシミュレーションと確定申告の手順を解説。',
    category: '医療費控除',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'furusato-nozei-genjo-sagaru': {
    slug: 'furusato-nozei-genjo-sagaru',
    title: 'ふるさと納税の上限額が下がる5つのケース',
    description: '「上限ギリギリまで寄附したのに自己負担が2,000円を超えた」を防ぐ。住宅ローン控除・iDeCo・医療費控除等でふるさと納税上限が下がるケースを完全解説。',
    category: 'ふるさと納税',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'ideco-setsuzei-ikura': {
    slug: 'ideco-setsuzei-ikura',
    title: 'iDeCoでいくら節税できる？年収別シミュレーション',
    description: 'iDeCoの掛け金が全額所得控除になる節税効果を年収別に計算。年収400・600・800・1000万円のシミュレーションと手続き方法を解説。',
    category: 'iDeCo',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'tokutei-shishutsu-kojo-suit': {
    slug: 'tokutei-shishutsu-kojo-suit',
    title: '特定支出控除でスーツ代を経費にする方法',
    description: 'サラリーマンでもスーツ代・資格取得費・業務書籍代を確定申告で経費にできる「特定支出控除」を詳しく解説。会社の証明書の取り方も。',
    category: '特定支出控除',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'seimei-hoken-kojo-waku': {
    slug: 'seimei-hoken-kojo-waku',
    title: '生命保険料控除の枠を使い切る方法',
    description: '生命保険料控除は一般・介護医療・個人年金の3枠。各枠の計算方法と節税効果を最大化するための保険の組み合わせ方を解説。',
    category: '生命保険料控除',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'iryohi-vs-selfmedication': {
    slug: 'iryohi-vs-selfmedication',
    title: '医療費控除とセルフメディケーション税制どっちが得？',
    description: '医療費控除（10万円超）とセルフメディケーション税制（1.2万円超のOTC薬）を徹底比較。どちらを選ぶべきか判断フローチャート付き。',
    category: 'セルフメディケーション',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'fukugyou-akaji-soneki-tsusan': {
    slug: 'fukugyou-akaji-soneki-tsusan',
    title: '副業の赤字で節税できる？損益通算の条件',
    description: '副業が事業所得なら給与所得と損益通算できる。雑所得との違い・損益通算の条件・税務署に認められるための帳簿管理を解説。',
    category: '副業・確定申告',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'fukugyou-20man-juminzei': {
    slug: 'fukugyou-20man-juminzei',
    title: '副業20万円以下でも住民税の申告は必要',
    description: '副業所得20万円以下は所得税の確定申告が不要でも、住民税の申告は必要です。申告漏れを防ぐ手順と普通徴収で副業をバレにくくする方法を解説。',
    category: '副業・確定申告',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  // Phase 2: 共働き クラスター追加分
  'pair-loan-setsuzei': {
    slug: 'pair-loan-setsuzei',
    title: 'ペアローンの節税メリットと注意点｜共働き夫婦が知るべき控除の仕組み',
    description: '共働き夫婦がペアローンで住宅を購入する場合の住宅ローン控除の仕組み・夫婦それぞれの控除額の計算方法・注意点を解説。',
    category: '共働き節税',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'tomobataraki-hoken-koujo': {
    slug: 'tomobataraki-hoken-koujo',
    title: '共働き夫婦の保険料控除、枠を使い切る方法｜夫婦で最大24万円控除',
    description: '生命保険料控除の枠は1人で最大12万円（所得税）。共働き夫婦で保険を最適配分すれば夫婦合計で最大24万円の控除が受けられる方法を解説。',
    category: '共働き節税',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'under16-juminzei-hikazei': {
    slug: 'under16-juminzei-hikazei',
    title: '16歳未満の子の扶養申告で住民税が非課税に？知られていない仕組みを解説',
    description: '16歳未満の子は所得税の扶養控除対象外ですが、住民税では「非課税判定」に影響します。共働き夫婦で誰の扶養に入れると住民税が安くなるかを解説。',
    category: '共働き節税',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'tomobataraki-fuyou-docchi': {
    slug: 'tomobataraki-fuyou-docchi',
    title: '共働きの子どもの扶養はどっちに入れる？',
    description: '共働き夫婦で子どもの扶養を夫・妻どちらに入れると節税効果が高いかを年収別に計算。大学生（19〜22歳）の特定扶養控除の活用法も解説。',
    category: '共働き節税',
    publishedAt: '2026-04-07',
    updatedAt: '2026-04-07',
    published: true,
  },
  'kabushiki-soneki-tsusan': {
    slug: 'kabushiki-soneki-tsusan',
    title: '株式の損益通算と繰越控除のやり方',
    description: '株式・投資信託の損失を利益と相殺する損益通算と、3年間繰り越せる繰越控除の申請方法を解説。特定口座・NISA口座との違いも整理。',
    category: '株式投資',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  // Phase 3: 退職金・iDeCo ピラー＋クラスター追加分
  'taishoku-ideco-saiteki': {
    slug: 'taishoku-ideco-saiteki',
    title: '退職金とiDeCoの最適な受取方法｜5年ルール・19年ルールをわかりやすく解説【2026年版】',
    description: '退職金とiDeCoの一時金受取に使える退職所得控除を最大活用するための「5年ルール」「19年ルール」を図解でわかりやすく解説。受取順序別の税額比較付き。',
    category: 'iDeCo・退職',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'taishoku-shotoku-koujo-keisan': {
    slug: 'taishoku-shotoku-koujo-keisan',
    title: '退職所得控除の計算方法｜勤続年数別の早見表と計算例',
    description: '退職所得控除の計算式（勤続20年以下: 40万×年数、20年超: 800万+70万×(年数-20)）を早見表と具体例で解説。障害者特例・端数処理も説明。',
    category: 'iDeCo・退職',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'ideco-5nen-rule': {
    slug: 'ideco-5nen-rule',
    title: 'iDeCoの5年ルールとは？退職金との受取順序で税金が変わる仕組み',
    description: 'iDeCoの一時金を退職金の5年後に受け取ると退職所得控除を二重に使える「5年ルール（2017年改正）」と「19年ルール（2022年改正）」の違いと活用法。',
    category: 'iDeCo・退職',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'ideco-uketori-ikkatsu-nenkin': {
    slug: 'ideco-uketori-ikkatsu-nenkin',
    title: 'iDeCoは一括と年金どっちが得？年齢・金額別の最適解',
    description: 'iDeCoの受取方法は「一時金（退職所得）」「年金（雑所得）」「併用」の3択。年齢・受取総額・他の年金収入によって最適解が変わる仕組みを解説。',
    category: 'iDeCo・退職',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'taishoku-mae-setsuzei-checklist': {
    slug: 'taishoku-mae-setsuzei-checklist',
    title: '50代で退職する前にやるべき節税準備チェックリスト',
    description: '退職前の節税準備12項目：iDeCo受取順序・退職所得控除の最大活用・健康保険の任意継続vs国民健康保険・ふるさと納税の使い切りなどを解説。',
    category: 'iDeCo・退職',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'taishokukin-zeikin-keisan': {
    slug: 'taishokukin-zeikin-keisan',
    title: '退職金にかかる税金はいくら？1,000万〜3,000万の計算例',
    description: '退職金の手取りを決める「退職所得控除」「1/2課税」の仕組みと、勤続年数別・退職金別の税額早見表。iDeCo一時金との合算計算も解説。',
    category: 'iDeCo・退職',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'ideco-taishokukin-ukewatashi': {
    slug: 'ideco-taishokukin-ukewatashi',
    title: 'iDeCoと退職金の受取順序で税金が100万円変わる',
    description: '退職金とiDeCoの一時金を同時に受け取ると退職所得控除が重複して損をします。受取時期を5年以上ずらすだけで最大100万円以上の節税になる仕組みを解説。',
    category: 'iDeCo・退職',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'zaitaku-kinmu-kojo': {
    slug: 'zaitaku-kinmu-kojo',
    title: '在宅勤務の費用は控除できない？',
    description: '会社員のテレワーク費用は給与所得控除に含まれ、原則として別途控除できません。例外となる特定支出控除や副業がある場合の按分方法を解説。',
    category: '在宅勤務',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'nenshu-500man-setsuzei-plan': {
    slug: 'nenshu-500man-setsuzei-plan',
    title: '年収500万円の手取りを最大化する節税プラン',
    description: '年収500万円の税負担と使える節税手段を完全解説。ふるさと納税・iDeCo・各種控除の組み合わせで年10〜20万円の節税も可能。家族構成別プランも掲載。',
    category: '年収別節税',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'nenshu-1000man-setsuzei-12sen': {
    slug: 'nenshu-1000man-setsuzei-12sen',
    title: '年収1000万のサラリーマンが使える節税対策12選',
    description: '年収1,000万円の会社員の税負担は約190万円。iDeCo・ふるさと納税・各種控除を組み合わせた節税対策12選と年30万円以上の節税シミュレーション。',
    category: '年収別節税',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'yokaigo-shogaisha-kojo': {
    slug: 'yokaigo-shogaisha-kojo',
    title: '要介護認定で障害者控除が使える',
    description: '障害者手帳がなくても要介護2〜3以上の高齢者は市区町村に申請するだけで障害者控除（27〜75万円）が使えます。申請方法と節税効果を解説。',
    category: '障害者控除',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'tokutei-fuyou-kojo-2026': {
    slug: 'tokutei-fuyou-kojo-2026',
    title: '特定扶養控除と特定親族特別控除の違い',
    description: '2026年税制改正で新設された「特定親族特別控除」と従来の「特定扶養控除」の違いを解説。大学生の子どもがいる家庭が取るべき対応もわかります。',
    category: '扶養控除',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'hitoriooya-kojo-jouken': {
    slug: 'hitoriooya-kojo-jouken',
    title: 'ひとり親控除の条件と申請方法',
    description: '2020年改正で男女・未婚問わず使えるようになった「ひとり親控除」（35万円）の要件・寡婦控除との違い・年末調整での申請方法を解説。',
    category: 'ひとり親控除',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'jishin-hoken-kojo-kakikata': {
    slug: 'jishin-hoken-kojo-kakikata',
    title: '地震保険料控除の書き方と上限額',
    description: '地震保険料控除（所得税5万円・住民税2.5万円が上限）の計算方法・年末調整での記入方法・控除証明書の見方を図解で解説。',
    category: '地震保険料控除',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'selfmedication-taishoyaku': {
    slug: 'selfmedication-taishoyaku',
    title: 'セルフメディケーション税制の対象薬の見分け方',
    description: 'スイッチOTC医薬品の見分け方はレシートの「★」マーク。対象薬の具体例・申請要件・通常の医療費控除との使い分け方を解説。',
    category: 'セルフメディケーション',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'fukugyou-keihi-dokomade': {
    slug: 'fukugyou-keihi-dokomade',
    title: '副業の経費はどこまで認められる？',
    description: '副業の経費として認められる支出の基準・家事按分の計算方法・税務調査で否認されないための記録の残し方を完全解説。',
    category: '副業・確定申告',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'aoiro-shinkoku-65man': {
    slug: 'aoiro-shinkoku-65man',
    title: '青色申告で65万円控除を受ける条件と手順',
    description: '青色申告の65万円特別控除を受けるには複式簿記＋e-Tax提出が必要。白色申告との節税効果の差・実務手順を具体的に解説。',
    category: 'フリーランス節税',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'bekkyo-oya-fuyou-setsuzei': {
    slug: 'bekkyo-oya-fuyou-setsuzei',
    title: '別居の親を扶養に入れて節税する方法',
    description: '別居でも仕送りの実態があれば扶養控除（48〜58万円）が使えます。仕送りの証明方法・老人扶養控除の節税効果・兄弟での分担方法を解説。',
    category: '扶養控除',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'haito-kojo-zekin-torimodosu': {
    slug: 'haito-kojo-zekin-torimodosu',
    title: '配当控除で税金を取り戻す',
    description: '国内株式配当は総合課税で申告すると配当控除（10%）が使えます。有利になる年収のボーダー・確定申告の手順・外国株との違いを解説。',
    category: '株式投資',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'juutaku-loan-furusato-heiyou': {
    slug: 'juutaku-loan-furusato-heiyou',
    title: '住宅ローン控除とふるさと納税は併用できる',
    description: '住宅ローン控除とふるさと納税は原則併用可能ですが、ローン控除で所得税が0円になるとふるさと納税の上限が下がることがあります。正確な計算方法を解説。',
    category: '住宅ローン控除',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'zason-kojo-shinkoku': {
    slug: 'zason-kojo-shinkoku',
    title: '雑損控除の申請方法と計算例',
    description: '台風・地震・盗難による被害を所得から控除できる雑損控除の計算式・申請方法・災害減免法との比較を具体的な計算例付きで解説。',
    category: '雑損控除',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'taishokukin-zekin-keisan': {
    slug: 'taishokukin-zekin-keisan',
    title: '退職金にかかる税金はいくら？',
    description: '退職金の税金計算（退職所得控除＋1/2課税）を勤続年数別シミュレーションで解説。手取りを最大化する受け取り方の工夫も紹介。',
    category: '退職・年金',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'ideco-nisa-docchi': {
    slug: 'ideco-nisa-docchi',
    title: 'iDeCoとNISAどっちを優先すべき？',
    description: 'iDeCoは即時節税、NISAは将来の運用益が非課税と目的が違います。所得・流動性・目的別にどちらを優先すべきか判断基準と最適な組み合わせを解説。',
    category: 'iDeCo',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'kakutei-shinkoku-shinai-donatsu': {
    slug: 'kakutei-shinkoku-shinai-donatsu',
    title: '確定申告しないとどうなる？',
    description: '確定申告の義務があるのに申告しないと無申告加算税（5〜20%）＋延滞税が発生します。発覚するきっかけ・ペナルティの種類・期限後申告の対処法を解説。',
    category: '副業・確定申告',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'shokibo-kyosai-salaryman': {
    slug: 'shokibo-kyosai-salaryman',
    title: '小規模企業共済はサラリーマンでも使える？',
    description: '小規模企業共済は個人事業主・役員向けで純粋な会社員は加入不可。副業で開業届を出した場合の加入条件と、サラリーマンが使える類似制度を解説。',
    category: 'フリーランス節税',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'gensen-choshuhyo-mikata': {
    slug: 'gensen-choshuhyo-mikata',
    title: '源泉徴収票の見方と控除漏れの見つけ方',
    description: '源泉徴収票の各項目の意味を解説。「所得控除の合計額」が少ない場合は控除漏れの可能性あり。過去5年分の還付申告で取り戻す方法も紹介。',
    category: 'サラリーマン節税',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'nenmatsu-kakekomi-setsuzei': {
    slug: 'nenmatsu-kakekomi-setsuzei',
    title: '年末の駆け込み節税リスト',
    description: '12月31日が締め切りの節税手段まとめ。ふるさと納税の駆け込み・株式の損出し・NISAの消化確認など年末にやるべきことをリスト化。',
    category: '年末調整',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'shussan-ikukyu-kojo': {
    slug: 'shussan-ikukyu-kojo',
    title: '出産・育休でもらえるお金と使える控除',
    description: '出産育児一時金・出産手当金・育児休業給付金は全額非課税。分娩・妊婦検診・不妊治療の医療費控除の計算方法と、育休中の年末調整の注意点を解説。',
    category: '医療費控除',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'tokutei-shishutsu-taiken': {
    slug: 'tokutei-shishutsu-taiken',
    title: '特定支出控除を実際に申請してみた体験談',
    description: '特定支出控除の申請フロー・会社の証明書取得の実体験・控除金額の計算例を紹介。「給与所得控除の1/2の壁」をどう超えるかも解説。',
    category: '特定支出控除',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'telework-denkidai-kojo': {
    slug: 'telework-denkidai-kojo',
    title: 'テレワークの電気代は控除できる？',
    description: '会社員のテレワーク電気代は原則控除不可（給与所得控除に含まれる）。テレワーク手当の非課税範囲と副業・フリーランスがいる場合の按分方法を解説。',
    category: '在宅勤務',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'ninchisho-oya-shogaisha-kojo': {
    slug: 'ninchisho-oya-shogaisha-kojo',
    title: '認知症の親がいる家庭の節税',
    description: '認知症で要介護の親は障害者控除（27〜75万円）＋老人扶養控除（48〜58万円）を組み合わせると最大133万円の控除が可能。申請方法を解説。',
    category: '障害者控除',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'freelance-kazoku-kyuyo': {
    slug: 'freelance-kazoku-kyuyo',
    title: 'フリーランスが家族に給与を払って節税する方法',
    description: '青色申告の「専従者給与」を使うと家族への給与を全額経費にできます。要件・適正給与の決め方・白色申告の専従者控除との比較を解説。',
    category: 'フリーランス節税',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'shougaku-genka-shokyaku': {
    slug: 'shougaku-genka-shokyaku',
    title: '少額減価償却資産の特例でパソコンを一括経費に',
    description: '青色申告者は30万円未満のPCや機材を購入年に一括経費化できます。通常の減価償却との比較・上限300万円の注意点・白色申告との違いを解説。',
    category: 'フリーランス節税',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  '103man-kabe-123man-kaisei': {
    slug: '103man-kabe-123man-kaisei',
    title: '103万円の壁→123万円に変更！2026年税制改正',
    description: '2026年税制改正で非課税ラインが103万円から123万円に拡大。パート・学生アルバイトへの影響・配偶者控除への波及・年末調整の対応方法を解説。',
    category: '年末調整',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'nenkin-kakutei-shinkoku': {
    slug: 'nenkin-kakutei-shinkoku',
    title: '年金受給者の確定申告は必要？',
    description: '65歳以上・年金400万円以下・他の所得20万円以下なら確定申告不要。ただし医療費控除・障害者控除等を申告すれば還付が受けられるケースも解説。',
    category: '退職・年金',
    publishedAt: '2026-04-08',
    updatedAt: '2026-04-08',
    published: true,
  },
  'iryouhi-self-medication-hikaku': {
    slug: 'iryouhi-self-medication-hikaku',
    title: '医療費控除とセルフメディケーション税制どっちが得？判定フローチャートと年収別シミュレーション【2026年版】',
    description: '医療費控除（10万円超）とセルフメディケーション税制（1.2万円超のスイッチOTC薬）を徹底比較。年収500万・700万・1,000万のシミュレーションと判定フローチャートで、あなたに有利な制度がわかります。',
    category: '医療費控除',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'iryouhi-koujo-urawaza': {
    slug: 'iryouhi-koujo-urawaza',
    title: '医療費控除の裏技7選｜通院交通費・家族合算・10万円以下でも使えるケース',
    description: '意外と知らない医療費控除の裏技7選。通院交通費・デンタルローン・家族合算・総所得200万円未満の5%ルールなど、控除額を最大化するテクニックを解説。',
    category: '医療費控除',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'self-medication-taishou-list': {
    slug: 'self-medication-taishou-list',
    title: 'セルフメディケーション税制の対象医薬品リスト｜ドラッグストアで見分ける方法',
    description: 'セルフメディケーション税制の対象となるスイッチOTC医薬品の見分け方と具体的なリスト。レシートの★マーク・商品例・申請要件をわかりやすく解説。',
    category: 'セルフメディケーション',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'shika-kyousei-iryouhi-koujo': {
    slug: 'shika-kyousei-iryouhi-koujo',
    title: '子どもの歯科矯正は医療費控除の対象？条件と計算例をわかりやすく解説',
    description: '子どもの歯科矯正費用は原則として医療費控除の対象です。審美目的との違い・デンタルローンの扱い・計算例を詳しく解説。家族合算で控除額を最大化する方法も紹介。',
    category: '医療費控除',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'fukugyou-20man-rule': {
    slug: 'fukugyou-20man-rule',
    title: '副業20万円以下でも申告が必要な3つのケース',
    description: '副業所得20万円以下でも確定申告が必要なケースを解説。住民税の申告義務・本業と合わせて申告する場合・損益通算をしたい場合など3つのパターンを具体例付きで説明。',
    category: '副業・確定申告',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'jigyou-shotoku-vs-zatsu-shotoku': {
    slug: 'jigyou-shotoku-vs-zatsu-shotoku',
    title: '事業所得と雑所得の違い｜2022年改正後の判断基準',
    description: '2022年の国税庁改正で明確化された事業所得と雑所得の判断基準を解説。収入300万円・帳簿保存・継続性の3要素と、事業所得として認められると使える損益通算の節税メリット。',
    category: '副業・確定申告',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'fukugyou-keihi-ichiran': {
    slug: 'fukugyou-keihi-ichiran',
    title: '副業の経費にできるもの一覧｜業種別の目安と注意点',
    description: '副業の経費として認められる費用の一覧を業種別に解説。PC・通信費・書籍・交通費・家賃按分の計算方法と、税務調査で否認されないための記録の残し方も紹介。',
    category: '副業・確定申告',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'fukugyou-barenai-houhou': {
    slug: 'fukugyou-barenai-houhou',
    title: '副業が会社にバレない方法｜住民税の普通徴収切替え手順',
    description: '副業が会社にバレる原因は住民税の増加。確定申告書で住民税を「普通徴収」に切り替えることで副業分の住民税が給与天引きされなくなります。具体的な手順と注意点を解説。',
    category: '副業・確定申告',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'souzoku-zei-guide': {
    slug: 'souzoku-zei-guide',
    title: '相続税はいくらからかかる？基礎控除・税率・計算方法を完全解説【2026年版】',
    description: '相続税の基礎控除（3,000万円+600万円×相続人数）の計算から税率表・特例まで完全解説。配偶者軽減・小規模宅地特例・生命保険非課税枠で節税できる方法も紹介。',
    category: '相続税',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'souzoku-kiso-koujo': {
    slug: 'souzoku-kiso-koujo',
    title: '相続税の基礎控除とは？法定相続人の数え方と計算例',
    description: '相続税の基礎控除「3,000万円+600万円×法定相続人数」の計算方法を解説。養子・代襲相続人の数え方・相続放棄した場合の扱いも詳しく説明。',
    category: '相続税',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'souzoku-haigusha-keigen': {
    slug: 'souzoku-haigusha-keigen',
    title: '配偶者の税額軽減で相続税が0円に？条件と落とし穴',
    description: '配偶者が相続する財産が1億6,000万円以下または法定相続分以下なら相続税が0円になる配偶者税額軽減の条件・手続き・二次相続の落とし穴を解説。',
    category: '相続税',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'shokibo-takuchi-tokurei': {
    slug: 'shokibo-takuchi-tokurei',
    title: '小規模宅地等の特例をわかりやすく解説｜80%減額の条件',
    description: '居住用土地（330㎡以内）の評価額が最大80%減額される「小規模宅地等の特例」の適用条件・家なき子特例・事業用宅地との違いを具体例付きで解説。',
    category: '相続税',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'seizen-zouyo-110man': {
    slug: 'seizen-zouyo-110man',
    title: '生前贈与の110万円枠を活用した相続対策｜2024年改正の影響',
    description: '2024年税制改正で相続前贈与の持ち戻し期間が3年から7年に延長。それでも生前贈与が有効な理由・早期開始のメリット・相続時精算課税との比較を解説。',
    category: '相続税',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  // Phase 6: ふるさと納税上限
  'furusato-limit-seikaku-keisan': {
    slug: 'furusato-limit-seikaku-keisan',
    title: 'ふるさと納税の上限額を正確に計算する方法｜iDeCo・住宅ローン控除の影響も反映【2026年版】',
    description: '年収・家族構成に加えてiDeCo・住宅ローン控除・医療費控除を考慮したふるさと納税上限額の計算方法を解説。簡易計算機では出ない正確な上限をシミュレーション。',
    category: 'ふるさと納税',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'furusato-ideco-heiyou': {
    slug: 'furusato-ideco-heiyou',
    title: 'ふるさと納税とiDeCoを併用すると上限はいくら下がる？年収別の影響額',
    description: 'iDeCoに加入するとふるさと納税の上限が下がる理由を計算式付きで解説。年収400〜800万円の具体的な影響額と、それでもiDeCoを優先すべき理由。',
    category: 'ふるさと納税',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'furusato-juutaku-loan-heiyou': {
    slug: 'furusato-juutaku-loan-heiyou',
    title: 'ふるさと納税と住宅ローン控除の併用｜上限が下がるケースと対処法',
    description: '住宅ローン控除を受けているとふるさと納税の上限が下がる場合がある。その仕組み・影響額の計算方法と、住宅購入後のふるさと納税戦略を解説。',
    category: 'ふるさと納税',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'furusato-one-stop-vs-kakutei': {
    slug: 'furusato-one-stop-vs-kakutei',
    title: 'ワンストップ特例と確定申告どっちが得？5自治体超えたらどうする？',
    description: 'ふるさと納税のワンストップ特例と確定申告の違い・どちらが有利か・5自治体を超えた場合の対応・医療費控除と併用する際の注意点を徹底解説。',
    category: 'ふるさと納税',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'furusato-nenmatsu-kakekomi': {
    slug: 'furusato-nenmatsu-kakekomi',
    title: 'ふるさと納税の年末駆け込みガイド｜12月に間に合わせる方法',
    description: 'ふるさと納税の締め切りは12月31日。年末ギリギリでも間に合う手続き方法・クレジットカード決済の締め切り・ワンストップ特例の申請期限を解説。',
    category: 'ふるさと納税',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  // Phase 7: 不動産売却
  'fudousan-baikyaku-zeikin-guide': {
    slug: 'fudousan-baikyaku-zeikin-guide',
    title: '不動産売却にかかる税金と節税方法を完全解説｜譲渡所得税の計算から特例まで【2026年版】',
    description: '不動産売却の譲渡所得税（長期・短期の税率の違い）・3,000万円特別控除・取得費不明時の対処法・相続不動産の特例など、節税に必要な知識を完全解説。',
    category: '不動産',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'fudousan-3000man-tokubetsu-koujo': {
    slug: 'fudousan-3000man-tokubetsu-koujo',
    title: 'マイホーム売却の3,000万円特別控除｜条件・手続き・注意点',
    description: '居住用財産を売却する際の3,000万円特別控除の適用条件・転居後の期限・確定申告の手続き・前年・前々年の適用制限など注意点を詳しく解説。',
    category: '不動産',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'fudousan-shutoku-hi-fumei': {
    slug: 'fudousan-shutoku-hi-fumei',
    title: '取得費がわからない不動産の売却｜概算取得費5%ルールと損しない方法',
    description: '不動産の購入書類を紛失した場合の「概算取得費（売却価格×5%）」の使い方・実際の取得費との比較・書類を探す方法・税務調査への対策を解説。',
    category: '不動産',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'souzoku-fudousan-baikyaku': {
    slug: 'souzoku-fudousan-baikyaku',
    title: '相続した不動産を売却する場合の税金｜取得費加算の特例と空き家特例',
    description: '相続不動産の売却に使える「取得費加算の特例」（3年10ヶ月以内）と「相続空き家の3,000万円特別控除」の適用条件・手続き・注意点を解説。',
    category: '不動産',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'fudousan-chouki-tanki': {
    slug: 'fudousan-chouki-tanki',
    title: '不動産の長期譲渡と短期譲渡の違い｜税率が2倍になる所有期間の判定',
    description: '不動産売却の税率が変わる「5年超（長期20.315%）」と「5年以下（短期39.63%）」の判定基準・注意点・所有期間を延ばして節税するメリットを解説。',
    category: '不動産',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
  'fudousan-sonshitsu-tsusan': {
    slug: 'fudousan-sonshitsu-tsusan',
    title: '不動産売却で損失が出た場合の確定申告｜損益通算で税金を取り戻す方法',
    description: 'マイホーム売却損の「損益通算」と「3年繰越控除」の仕組み・給与所得との相殺方法・投資用不動産の損失との違い・確定申告の手続きを解説。',
    category: '不動産',
    publishedAt: '2026-04-15',
    updatedAt: '2026-04-15',
    published: true,
  },
};

export function getStaticArticle(slug: string): StaticArticle | null {
  return staticArticles[slug] ?? null;
}

export function getPublishedStaticArticles(): StaticArticle[] {
  return Object.values(staticArticles).filter((a) => a.published);
}
